Add toggle for strawpoll options to be added by delegates
MaxwellBo/Muncoordinated-2 pull request #155
Opened 2021-06-11 12:07 UTC by kumar-ish

As per #84, we want the ability for the conference organiser to toggle an option that lets delegates add their options to strawpolls (but does not let them delete them). This pull request implements this. 

Demo below:

![output](https://user-images.githubusercontent.com/47245900/121683814-3c2e3880-cb01-11eb-9cc0-e2a31e6ba812.gif)

2021-06-11 12:31 UTC, kumar-ish commented on src/components/Strawpoll.tsx
> +
```suggestion
```

2021-07-15 10:34 UTC, MaxwellBo requested changes

2021-07-15 10:34 UTC, MaxwellBo commented on database.rules.json
> +                ".write": "newData.exists() && data.parent().parent().child('addingOptionsIsPublic').val() === true",
nit: can this be `optionsArePublic`? Seems more inline with the convention of `<type>(Is|Are)Public`

2021-07-15 10:34 UTC, MaxwellBo commented on database.rules.json
> +                ".write": "newData.exists() && data.parent().parent().child('addingOptionsIsPublic').val() === true",
- [ ] TODO: @MaxwellBo Update the `database.rules.json` in the Firebase console after this change is merged

2021-07-15 10:34 UTC, MaxwellBo commented on src/components/Strawpoll.tsx
> +              <Checkbox
Should this have a `loading={!strawpoll}`?

2021-07-15 10:34 UTC, MaxwellBo commented on src/components/Strawpoll.tsx
> +                checked={strawpoll ? (strawpoll.addingOptionsIsPublic || false) : false}
I think this could be simplified to `checked={strawpoll?.addingOptionsIsPublic}`

2022-07-10 02:14 UTC, merged