prosedual Motion Button Alignment
MaxwellBo/Muncoordinated-2 pull request #184
Opened 2022-11-15 16:54 UTC by JulianWww

When a motion is procedural, there is no need to have an abstain button be present. Furthermore the three sections will now take 1/3 of the available space each. Unless there are only two in which case they will take up half.

2022-11-16 07:09 UTC, MaxwellBo commented on src/pages/Motions.tsx
> +          {procedural(motionData.type)? null :
```suggestion
          {procedural(motionData.type) &&
```

2022-11-16 07:10 UTC, MaxwellBo approved these changes
Looks good to me with the ternary to `&&` change!

Thank-you for the contribution 😀

2022-11-18 05:30 UTC, MaxwellBo requested changes
One quick change required with the ternary.

2022-11-18 09:37 UTC, JulianWww commented
Changed sorry my bad

2022-11-28 00:16 UTC, JulianWww reviewed
Change has been made don't know how to mark it if that is possible

2022-11-28 03:10 UTC, MaxwellBo approved these changes

2022-11-28 03:10 UTC, merged

2022-11-28 03:10 UTC, MaxwellBo commented
@JulianWww All good! Will merge.